name: Universal Code Runner

on:
  push:
    paths:
      - 'scripts/**'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install compilers
      run: |
        sudo apt update
        sudo apt install -y build-essential default-jdk g++ gcc

    - name: Run all scripts
      run: |
        for file in scripts/*; do
          echo "------------------------------"
          echo "Running $file"
          ext="${file##*.}"
          case $ext in
            py)
              python "$file"
              ;;
            c)
              # Remove problematic dots from output name
              OUTPUT="${file##*/}"
              OUTPUT="${OUTPUT%.c}"
              gcc "$file" -o "$OUTPUT" && "./$OUTPUT"
              ;;
            cpp)
              OUTPUT="${file##*/}"
              OUTPUT="${OUTPUT%.cpp}"
              g++ "$file" -o "$OUTPUT" && "./$OUTPUT"
              ;;
            java)
              cd scripts
              FILENAME="${file##*/}"           # Test.java
              CLASSNAME="${FILENAME%.java}"    # Test
              javac "$FILENAME"
              java "$CLASSNAME"
              cd ..
              ;;
            *)
              echo "Unsupported file type: $file"
              ;;
          esac
        done

